# Generated by Django 5.0.3 on 2024-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesstour', '0002_chess_tournament_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess_tournament',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
    ]
