# Generated by Django 5.0.3 on 2024-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesstour', '0006_alter_chess_tournament_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess_player',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
