# Generated by Django 5.0.3 on 2024-07-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesstour', '0007_alter_chess_player_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess_game',
            name='white_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='chesstour.chess_player'),
        ),
    ]
